server:
  port: 8088
  servlet:
    context-path: "/api"
spring:
  # Redis配置
  data:
    redis:
      database: 1
      host: localhost
      port: 6379
      # 读超时
      timeout: 3000
      # 连接超时
      connectTimeout: 5000
      # Lettuce连接池
      lettuce:
        pool:
          # 最小空闲连接
          min-idle: 5
          # 最大空闲连接
          max-idle: 10
          # 最大连接数
          max-active: 100
          # 连接分配应该阻塞的最大时间
          max-wait: 2000
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    stream:
      username: guest
      password: guest
      virtual-host: /
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
  activiti:
    #1.flase:activiti在启动时，对比数据库表中保存的版本，如果没有表或者版本不匹配，将抛出异常
    #2.true:默认值。activiti会对数据库中所有表进行更新操作。如果表不存在，则自动创建
    #3.create_drop: fiactiviti启动时创建表，在关闭时删除表（必须手动关闭引擎，才能删除表)
    #4.drop-create:/iactiviti启动时删除原来的旧表，然后在创建新表（不需要手动关闭引擎)
    database-schema-update: true
    #activiti7默认不生成历史信思表，开启历史表
    db-history-used: true
    #记录历史等级可配置的历史级别有none,activity,audit,full
    #none:不保存任何的历史数据，因此，在流程执行过程中，这是最高效的。
    #activity:级别高于none，保存流程实例与流程行为，其他数据不保存。
    #audit:除activity级别会保存的数据外，还会保存全部的流程任务及其属性。audit/history的默认值。
    #full:保存历史数据的最高级别，除了会保存audit级别的数据外，还会保存其他全部流程相关的细节数据，包括一些流程参数等。
    history-level: full
    check-process-definitions: true
    # 流程文件默认存放路径classpath*:**/processes/
    #    process-definition-location-prefix: classpath*:**/processes/
    # 流程文件默认文件后缀 **.bpmn20.xml", "**.bpmn"
    deployment-mode: never-fail
  #    process-definition-location-suffixes: **.bpmn20.xml", "**.bpmn"
  Thymeleaf:
    cache: false
    suffix: .html
  web:
    resources:
      static-locations: classpath:/templates/,classpath:/static/image/
logging:
  level:
    cn:
      api:
        mapper: debug
mybatis:
  configuration:
    auto-mapping-behavior: full
    use-column-label: true
  mapper-locations: classpath:mapper/*.xml

